// frontend/src/pages/Login/index.tsx
import React, { useEffect, useCallback } from 'react';
import { Form, Input, Button, Card, Checkbox, Spin, message } from 'antd';
import { useNavigate } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import { useConnectionStore } from '@/stores/connection';
import styles from './index.module.less';

const Login: React.FC = () => {
  const { t } = useTranslation();
  const navigate = useNavigate();
  const { login, isLoading, loadSavedConnection } = useConnectionStore();
  const [form] = Form.useForm();

  useEffect(() => {
    loadSavedConnection();
    
    const savedConnection = localStorage.getItem('graphdb_connection');
    if (savedConnection) {
      try {
        const connectionInfo = JSON.parse(savedConnection);
        form.setFieldsValue({
          username: connectionInfo.username,
          password: connectionInfo.password || '',
          rememberMe: true,
        });
      } catch (e) {
        console.error('Failed to parse saved connection', e);
      }
    }
  }, [form, loadSavedConnection]);

  const handleSubmit = async (values: {
    username: string;
    password: string;
    rememberMe: boolean;
  }) => {
    const { username, password, rememberMe } = values;
    
    try {
      await login(username, password, rememberMe);
      message.success(t('login.loginSuccess'));
      navigate('/');
    } catch (err: unknown) {
      const errorMessage = err instanceof Error ? err.message : t('login.loginFailed');
      message.error(errorMessage);
    }
  };

  const handleRememberMeChange = useCallback((checked: boolean) => {
    console.log('Remember me:', checked);
  }, []);

  return (
    <div className={styles.loginPage}>
      <Card className={styles.loginCard} title={t('login.title')}>
        <Spin spinning={isLoading}>
          <Form
            form={form}
            name="login"
            onFinish={handleSubmit}
            layout="vertical"
            initialValues={{
              username: 'root',
              rememberMe: false,
            }}
          >
            <Form.Item
              name="username"
              label={t('common.username')}
              rules={[{ required: true, message: t('login.usernameRequired') }]}
            >
              <Input placeholder={t('login.usernamePlaceholder')} />
            </Form.Item>

            <Form.Item
              name="password"
              label={t('common.password')}
              rules={[{ required: true, message: t('login.passwordRequired') }]}
            >
              <Input.Password placeholder={t('login.passwordPlaceholder')} />
            </Form.Item>

            <Form.Item name="rememberMe" valuePropName="checked">
              <Checkbox onChange={(e) => handleRememberMeChange(e.target.checked)}>
                {t('common.rememberMe')}
              </Checkbox>
            </Form.Item>

            <Form.Item>
              <Button type="primary" htmlType="submit" block loading={isLoading}>
                {t('common.login')}
              </Button>
            </Form.Item>
          </Form>
        </Spin>
      </Card>
    </div>
  );
};

export default Login;

// frontend/src/routes/login/+page.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { t } from '$i18n';
	import { goto } from '$app/navigation';
	import { connectionStore } from '$stores/connection';

	let username = $state('root');
	let password = $state('');
	let rememberMe = $state(false);
	let isLoading = $state(false);
	let errorMsg = $state('');
	let formValid = $derived(username.trim() && password.trim());

	onMount(() => {
		connectionStore.loadSavedConnection();
		const saved = localStorage.getItem('graphdb_connection');
		if (saved) {
			try {
				const info = JSON.parse(saved);
				if (info.username) username = info.username;
				if (info.password) password = info.password;
				rememberMe = true;
			} catch {
				/* ignore */
			}
		}
	});

	async function handleSubmit(e: Event) {
		e.preventDefault();
		if (!formValid) return;
		isLoading = true;
		errorMsg = '';
		try {
			await connectionStore.login(username, password, rememberMe);
			goto('/');
		} catch (err) {
			errorMsg = err instanceof Error ? err.message : t('login.loginFailed');
		} finally {
			isLoading = false;
		}
	}
</script>

<div
	class="min-h-screen flex items-center justify-center bg-gray-100 dark:bg-[#0B0F17] transition-colors duration-300"
>
	<div
		class="bg-white dark:bg-[#1C2333] rounded-lg shadow-md p-8 w-full max-w-sm transition-colors duration-300"
	>
		<h1
			class="text-2xl font-bold text-center text-gray-800 dark:text-gray-100 mb-6"
		>
			{t('app.title')}
		</h1>
		<form onsubmit={handleSubmit}>
			{#if errorMsg}
				<div
					class="mb-4 p-3 bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800 rounded text-red-600 dark:text-red-400 text-sm"
				>
					{errorMsg}
				</div>
			{/if}
			<div class="mb-4">
				<label
					class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1"
					for="username">{t('common.username')}</label
				>
				<input
					id="username"
					type="text"
					bind:value={username}
					class="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 bg-white dark:bg-[#1C2333] text-gray-800 dark:text-gray-200 rounded text-sm focus:outline-none focus:border-blue-500 focus:ring-1 focus:ring-blue-500"
					placeholder={t('login.usernamePlaceholder')}
					disabled={isLoading}
				/>
			</div>
			<div class="mb-4">
				<label
					class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1"
					for="password">{t('common.password')}</label
				>
				<input
					id="password"
					type="password"
					bind:value={password}
					class="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 bg-white dark:bg-[#1C2333] text-gray-800 dark:text-gray-200 rounded text-sm focus:outline-none focus:border-blue-500 focus:ring-1 focus:ring-blue-500"
					placeholder={t('login.passwordPlaceholder')}
					disabled={isLoading}
				/>
			</div>
			<div class="mb-4">
				<label
					class="flex items-center gap-2 text-sm text-gray-600 dark:text-gray-400"
				>
					<input
						type="checkbox"
						bind:checked={rememberMe}
						class="rounded dark:bg-gray-700"
					/>
					{t('common.rememberMe')}
				</label>
			</div>
			<button
				type="submit"
				class="w-full py-2 px-4 bg-blue-500 hover:bg-blue-600 text-white font-medium rounded text-sm transition-colors disabled:opacity-50 disabled:cursor-not-allowed cursor-pointer"
				disabled={!formValid || isLoading}
			>
				{isLoading ? t('common.loading') : t('common.login')}
			</button>
		</form>
	</div>
</div>
