// frontend/src/lib/components/layout/ProtectedRoute.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { t } from 'svelte-i18n';
  import { isAuthenticated, connectionStore } from '$stores/connection';
  import LoadingScreen from '$components/common/LoadingScreen.svelte';

  let { children } = $props();
  let checking = $state(true);

  onMount(async () => {
    let auth = false;
    const unsub = isAuthenticated.subscribe(v => auth = v)();
    if (!auth) {
      let store: { isConnected: boolean; isVerified: boolean } = { isConnected: false, isVerified: false };
      const unsub2 = connectionStore.subscribe(s => store = s)();
      if (store.isConnected && !store.isVerified) {
        await connectionStore.checkHealth();
      }
    }
    checking = false;
  });
</script>

{#if checking}
  <LoadingScreen />
{:else if $isAuthenticated}
  {@render children()}
{:else}
  <a href="/login">{$t('common.redirecting')}</a>
{/if}

// frontend/src/components/layout/ProtectedRoute.tsx
import React, { useEffect, useState } from 'react';
import { Navigate, useLocation } from 'react-router-dom';
import { useConnectionStore } from '@/stores/connection';
import LoadingScreen from '@/components/common/LoadingScreen';

const ProtectedRoute: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const { isConnected, isVerified, checkHealth } = useConnectionStore();
  const location = useLocation();
  const [isChecking, setIsChecking] = useState(true);

  useEffect(() => {
    const verifyConnection = async () => {
      if (isConnected && !isVerified) {
        await checkHealth();
      }
      setIsChecking(false);
    };

    verifyConnection();
  }, [isConnected, isVerified, checkHealth]);

  if (isChecking) {
    return <LoadingScreen />;
  }

  if (!isVerified) {
    return <Navigate to="/login" state={{ from: location }} replace />;
  }

  return <>{children}</>;
};

export default ProtectedRoute;
