// frontend/src/pages/DataBrowser/index.tsx
import React, { useEffect, useState } from 'react';
import {
  Card,
  Tabs,
  Select,
  Table,
  Pagination,
  Spin,
  Alert,
  Button,
  Space,
  Tooltip,
} from 'antd';
import {
  DatabaseOutlined,
  LinkOutlined,
  FilterOutlined,
  EyeOutlined,
  ReloadOutlined,
} from '@ant-design/icons';
import { useDataBrowserStore } from '@/stores/dataBrowser';
import { useSchemaStore } from '@/stores/schema';
import { dataBrowserService } from '@/services/dataBrowser';
import FilterPanel from './components/FilterPanel';
import StatisticsPanel from './components/StatisticsPanel';
import DetailModal from './components/DetailModal';
import type { VertexData, EdgeData } from '@/types/dataBrowser';
import type { TableColumnType } from 'antd';
import styles from './index.module.less';

const { TabPane } = Tabs;

const DataBrowser: React.FC = () => {
  const { currentSpace, tags, edgeTypes } = useSchemaStore();
  const {
    activeTab,
    selectedTag,
    selectedEdgeType,
    vertices,
    edges,
    vertexTotal,
    edgeTotal,
    vertexPage,
    edgePage,
    vertexPageSize,
    edgePageSize,
    vertexSort,
    edgeSort,
    filters,
    filterPanelVisible,
    loading,
    error,
    setActiveTab,
    setSelectedTag,
    setSelectedEdgeType,
    setVertices,
    setEdges,
    setVertexPage,
    setEdgePage,
    setVertexPageSize,
    setEdgePageSize,
    setVertexSort,
    setEdgeSort,
    toggleFilterPanel,
    setStatistics,
    showDetail,
    setLoading,
    setError,
  } = useDataBrowserStore();

  const [vertexProperties, setVertexProperties] = useState<string[]>([]);
  const [edgeProperties, setEdgeProperties] = useState<string[]>([]);

  // Load statistics on mount
  useEffect(() => {
    if (currentSpace) {
      loadStatistics();
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [currentSpace]);

  // Load data when dependencies change
  useEffect(() => {
    if (currentSpace && selectedTag) {
      loadVertices();
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [currentSpace, selectedTag, vertexPage, vertexPageSize, vertexSort, filters]);

  useEffect(() => {
    if (currentSpace && selectedEdgeType) {
      loadEdges();
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [currentSpace, selectedEdgeType, edgePage, edgePageSize, edgeSort, filters]);

  // Update properties when tag/edge type changes
  useEffect(() => {
    if (selectedTag && vertices.length > 0) {
      const props = Object.keys(vertices[0].properties);
      setVertexProperties(props);
    } else {
      setVertexProperties([]);
    }
  }, [selectedTag, vertices]);

  useEffect(() => {
    if (selectedEdgeType && edges.length > 0) {
      const props = Object.keys(edges[0].properties);
      setEdgeProperties(props);
    } else {
      setEdgeProperties([]);
    }
  }, [selectedEdgeType, edges]);

  const loadStatistics = async () => {
    if (!currentSpace) return;
    try {
      const stats = await dataBrowserService.getStatistics(currentSpace);
      setStatistics(stats);
    } catch (err) {
      console.error('Failed to load statistics:', err);
    }
  };

  const loadVertices = async () => {
    if (!currentSpace || !selectedTag) return;

    setLoading(true);
    setError(null);

    try {
      const response = await dataBrowserService.getVertices(
        currentSpace,
        selectedTag,
        vertexPage,
        vertexPageSize,
        vertexSort || { field: 'id', order: 'asc' },
        filters
      );
      setVertices(response.data, response.total);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to load vertices');
    } finally {
      setLoading(false);
    }
  };

  const loadEdges = async () => {
    if (!currentSpace || !selectedEdgeType) return;

    setLoading(true);
    setError(null);

    try {
      const response = await dataBrowserService.getEdges(
        currentSpace,
        selectedEdgeType,
        edgePage,
        edgePageSize,
        edgeSort || { field: 'id', order: 'asc' },
        filters
      );
      setEdges(response.data, response.total);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to load edges');
    } finally {
      setLoading(false);
    }
  };

  const handleTableChange = (
    _pagination: unknown,
    _filters: unknown,
    sorter: unknown
  ) => {
    const getField = (field: unknown): string => {
      if (Array.isArray(field)) {
        return String(field[0]);
      }
      return String(field ?? 'id');
    };

    const parseSorter = (s: unknown): { field: string; order: 'asc' | 'desc' } => {
      if (!s || typeof s !== 'object') {
        return { field: 'id', order: 'asc' };
      }
      const sorterObj = s as { field?: unknown; order?: 'ascend' | 'descend' | null };
      const field = getField(sorterObj.field);
      const order = sorterObj.order === 'ascend' ? 'asc' : 'desc';
      return { field, order };
    };

    const parsedSorter = parseSorter(sorter);

    if (activeTab === 'vertices') {
      setVertexSort(parsedSorter);
    } else {
      setEdgeSort(parsedSorter);
    }
  };

  const getVertexColumns = (): TableColumnType<VertexData>[] => {
    const baseColumns: TableColumnType<VertexData>[] = [
      {
        title: 'ID',
        dataIndex: 'id',
        key: 'id',
        width: 200,
        ellipsis: true,
        sorter: true,
      },
      {
        title: 'Tag',
        dataIndex: 'tag',
        key: 'tag',
        width: 120,
      },
    ];

    const propertyColumns = vertexProperties.map((prop) => ({
      title: prop,
      dataIndex: ['properties', prop],
      key: prop,
      ellipsis: true,
      sorter: true,
      render: (value: unknown) => String(value ?? '-'),
    }));

    const actionColumn: TableColumnType<VertexData> = {
      title: 'Action',
      key: 'action',
      width: 80,
      fixed: 'right',
      render: (_, record) => (
        <Tooltip title="View Detail">
          <Button
            icon={<EyeOutlined />}
            size="small"
            type="text"
            onClick={() => showDetail(record, 'vertex')}
          />
        </Tooltip>
      ),
    };

    return [...baseColumns, ...propertyColumns, actionColumn];
  };

  const getEdgeColumns = (): TableColumnType<EdgeData>[] => {
    const baseColumns: TableColumnType<EdgeData>[] = [
      {
        title: 'ID',
        dataIndex: 'id',
        key: 'id',
        width: 200,
        ellipsis: true,
        sorter: true,
      },
      {
        title: 'Type',
        dataIndex: 'type',
        key: 'type',
        width: 120,
      },
      {
        title: 'Source',
        dataIndex: 'src',
        key: 'src',
        width: 200,
        ellipsis: true,
      },
      {
        title: 'Target',
        dataIndex: 'dst',
        key: 'dst',
        width: 200,
        ellipsis: true,
      },
      {
        title: 'Rank',
        dataIndex: 'rank',
        key: 'rank',
        width: 80,
        sorter: true,
      },
    ];

    const propertyColumns = edgeProperties.map((prop) => ({
      title: prop,
      dataIndex: ['properties', prop],
      key: prop,
      ellipsis: true,
      sorter: true,
      render: (value: unknown) => String(value ?? '-'),
    }));

    const actionColumn: TableColumnType<EdgeData> = {
      title: 'Action',
      key: 'action',
      width: 80,
      fixed: 'right',
      render: (_, record) => (
        <Tooltip title="View Detail">
          <Button
            icon={<EyeOutlined />}
            size="small"
            type="text"
            onClick={() => showDetail(record, 'edge')}
          />
        </Tooltip>
      ),
    };

    return [...baseColumns, ...propertyColumns, actionColumn];
  };

  if (!currentSpace) {
    return (
      <div className={styles.container}>
        <Alert
          message="Please select a space first"
          description="You need to select a space to browse data"
          type="info"
          showIcon
        />
      </div>
    );
  }

  return (
    <div className={styles.container}>
      <Card className={styles.headerCard}>
        <div className={styles.header}>
          <h2>Data Browser</h2>
          <Space>
            <Button
              icon={<ReloadOutlined />}
              onClick={loadStatistics}
              loading={loading}
            >
              Refresh
            </Button>
            <Button
              icon={<FilterOutlined />}
              type={filterPanelVisible ? 'primary' : 'default'}
              onClick={toggleFilterPanel}
            >
              Filter
            </Button>
          </Space>
        </div>
      </Card>

      <div className={styles.content}>
        <div className={styles.main}>
          {error && (
            <Alert
              message={error}
              type="error"
              showIcon
              closable
              className={styles.error}
            />
          )}

          <Card className={styles.dataCard}>
            <Tabs activeKey={activeTab} onChange={(key) => setActiveTab(key as 'vertices' | 'edges')}>
              <TabPane
                tab={<span><DatabaseOutlined /> Vertices</span>}
                key="vertices"
              >
                <div className={styles.filterRow}>
                  <Select
                    placeholder="Select Tag"
                    value={selectedTag}
                    onChange={setSelectedTag}
                    style={{ width: 200 }}
                    allowClear
                    options={tags.map((tag) => ({
                      label: tag.name,
                      value: tag.name,
                    }))}
                  />
                </div>

                {filterPanelVisible && <FilterPanel properties={vertexProperties} />}

                <Spin spinning={loading}>
                  <Table
                    dataSource={vertices}
                    columns={getVertexColumns()}
                    rowKey="id"
                    pagination={false}
                    scroll={{ x: 'max-content' }}
                    size="small"
                    onChange={handleTableChange}
                  />
                  <div className={styles.pagination}>
                    <Pagination
                      current={vertexPage}
                      pageSize={vertexPageSize}
                      total={vertexTotal}
                      showSizeChanger
                      showTotal={(total) => `Total ${total} items`}
                      onChange={setVertexPage}
                      onShowSizeChange={(_, size) => setVertexPageSize(size)}
                    />
                  </div>
                </Spin>
              </TabPane>

              <TabPane
                tab={<span><LinkOutlined /> Edges</span>}
                key="edges"
              >
                <div className={styles.filterRow}>
                  <Select
                    placeholder="Select Edge Type"
                    value={selectedEdgeType}
                    onChange={setSelectedEdgeType}
                    style={{ width: 200 }}
                    allowClear
                    options={edgeTypes.map((type) => ({
                      label: type.name,
                      value: type.name,
                    }))}
                  />
                </div>

                {filterPanelVisible && <FilterPanel properties={edgeProperties} />}

                <Spin spinning={loading}>
                  <Table
                    dataSource={edges}
                    columns={getEdgeColumns()}
                    rowKey="id"
                    pagination={false}
                    scroll={{ x: 'max-content' }}
                    size="small"
                    onChange={handleTableChange}
                  />
                  <div className={styles.pagination}>
                    <Pagination
                      current={edgePage}
                      pageSize={edgePageSize}
                      total={edgeTotal}
                      showSizeChanger
                      showTotal={(total) => `Total ${total} items`}
                      onChange={setEdgePage}
                      onShowSizeChange={(_, size) => setEdgePageSize(size)}
                    />
                  </div>
                </Spin>
              </TabPane>
            </Tabs>
          </Card>
        </div>

        <div className={styles.sidebar}>
          <StatisticsPanel />
        </div>
      </div>

      <DetailModal />
    </div>
  );
};

export default DataBrowser;

// frontend/src/lib/pages/DataBrowser/DataBrowser.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { t } from 'svelte-i18n';
  import { get } from 'svelte/store';
  import { navigate } from 'svelte-routing';
  import { dataBrowserStore } from '$stores/dataBrowser';
  import { graphStore } from '$stores/graph';
  import { schemaStore } from '$stores/schema';
  import { dataBrowserService } from '$services/dataBrowser';
  import { formatCellValue } from '$utils/parseData';
  import PageSkeleton from '$components/common/PageSkeleton.svelte';
  import FilterPanel from './FilterPanel.svelte';
  import type { VertexData, EdgeData, Statistics } from '$types/dataBrowser';
  import type { Tag, EdgeType } from '$types/schema';

  let currentSpace = $state<string | null>(null);
  let tags = $state<Tag[]>([]);
  let edgeTypes = $state<EdgeType[]>([]);

  let activeTab = $state<'vertices' | 'edges'>('vertices');
  let selectedTag = $state<string | null>(null);
  let selectedEdgeType = $state<string | null>(null);
  let vertices = $state<VertexData[]>([]);
  let edges = $state<EdgeData[]>([]);
  let vertexTotal = $state(0);
  let edgeTotal = $state(0);
  let vertexPage = $state(1);
  let edgePage = $state(1);
  let vertexPageSize = $state(50);
  let edgePageSize = $state(50);
  let loading = $state(false);
  let error = $state<string | null>(null);
  let statistics = $state<Statistics | null>(null);
  let filterPanelVisible = $state(false);
  let detailModalVisible = $state(false);
  let detailData = $state<VertexData | EdgeData | null>(null);
  let detailType = $state<string | null>(null);

  let vertexProperties = $state<string[]>([]);
  let edgeProperties = $state<string[]>([]);
  let pageInitialized = $state(false);

  onMount(() => {
    const unsub1 = schemaStore.subscribe(s => {
      currentSpace = s.currentSpace;
      tags = s.tags;
      edgeTypes = s.edgeTypes;
    });
    const unsub2 = dataBrowserStore.subscribe(s => {
      activeTab = s.activeTab;
      selectedTag = s.selectedTag;
      selectedEdgeType = s.selectedEdgeType;
      vertices = s.vertices;
      edges = s.edges;
      vertexTotal = s.vertexTotal;
      edgeTotal = s.edgeTotal;
      vertexPage = s.vertexPage;
      edgePage = s.edgePage;
      vertexPageSize = s.vertexPageSize;
      edgePageSize = s.edgePageSize;
      loading = s.loading;
      error = s.error;
      statistics = s.statistics;
      filterPanelVisible = s.filterPanelVisible;
      detailModalVisible = s.detailModalVisible;
      detailData = s.detailData;
      detailType = s.detailType;
    });
    if (currentSpace) schemaStore.fetchTags(currentSpace);
    pageInitialized = true;
    return () => { unsub1(); unsub2(); };
  });

  async function loadVertices() {
    if (!currentSpace || !selectedTag) return;
    dataBrowserStore.setLoading(true);
    dataBrowserStore.setError(null);
    try {
      const activeFilters = get(dataBrowserStore).filters;
      const response = await dataBrowserService.getVertices(currentSpace, selectedTag, vertexPage, vertexPageSize, { field: 'id', order: 'asc' }, activeFilters);
      dataBrowserStore.setVertices(response.data, response.total);
      if (response.data.length > 0) vertexProperties = Object.keys(response.data[0].properties);
    } catch (err) {
      dataBrowserStore.setError(err instanceof Error ? err.message : 'Failed to load vertices');
    } finally {
      dataBrowserStore.setLoading(false);
    }
  }

  async function loadEdges() {
    if (!currentSpace || !selectedEdgeType) return;
    dataBrowserStore.setLoading(true);
    dataBrowserStore.setError(null);
    try {
      const activeFilters = get(dataBrowserStore).filters;
      const response = await dataBrowserService.getEdges(currentSpace, selectedEdgeType, edgePage, edgePageSize, { field: 'id', order: 'asc' }, activeFilters);
      dataBrowserStore.setEdges(response.data, response.total);
      if (response.data.length > 0) edgeProperties = Object.keys(response.data[0].properties);
    } catch (err) {
      dataBrowserStore.setError(err instanceof Error ? err.message : 'Failed to load edges');
    } finally {
      dataBrowserStore.setLoading(false);
    }
  }

  function applyFilters() {
    if (activeTab === 'vertices') {
      dataBrowserStore.setVertexPage(1);
      loadVertices();
    } else {
      dataBrowserStore.setEdgePage(1);
      loadEdges();
    }
  }

  async function loadStatistics() {
    if (!currentSpace) return;
    try {
      const stats = await dataBrowserService.getStatistics(currentSpace);
      dataBrowserStore.setStatistics(stats);
    } catch (err) { console.error('Failed to load statistics:', err); }
  }

  function handleTagChange(e: Event) {
    const val = (e.target as HTMLSelectElement).value || null;
    dataBrowserStore.setSelectedTag(val);
    if (val && currentSpace) loadVertices();
  }

  function handleEdgeTypeChange(e: Event) {
    const val = (e.target as HTMLSelectElement).value || null;
    dataBrowserStore.setSelectedEdgeType(val);
    if (val && currentSpace) loadEdges();
  }

  function handleTabChange(tab: 'vertices' | 'edges') {
    dataBrowserStore.setActiveTab(tab);
    if (tab === 'vertices' && currentSpace) { schemaStore.fetchTags(currentSpace); if (selectedTag) loadVertices(); }
    if (tab === 'edges' && currentSpace) { schemaStore.fetchEdgeTypes(currentSpace); if (selectedEdgeType) loadEdges(); }
  }

  function showDetail(data: VertexData | EdgeData, type: 'vertex' | 'edge') {
    dataBrowserStore.showDetail(data, type);
  }

  function viewInGraph(data: VertexData | EdgeData, type: 'vertex' | 'edge') {
    if (type === 'vertex') {
      const v = data as VertexData;
      graphStore.mergeGraphData({
        nodes: [{ id: String(v.id), tag: v.tag ?? 'unknown', properties: v.properties ?? {} }],
        edges: [],
      });
    } else {
      const e = data as EdgeData;
      const src = String(e.src);
      const dst = String(e.dst);
      graphStore.mergeGraphData({
        nodes: [
          { id: src, tag: 'unknown', properties: {} },
          { id: dst, tag: 'unknown', properties: {} },
        ],
        edges: [{ id: String(e.id), type: e.type ?? 'unknown', source: src, target: dst, rank: e.rank ?? 0, properties: e.properties ?? {} }],
      });
    }
    navigate('/graph');
  }
</script>

{#if !pageInitialized}
  <PageSkeleton />
{:else if currentSpace}
  <div class="flex flex-col h-full gap-4">
    <div class="bg-white dark:bg-[#1C2333] rounded-lg shadow-sm px-5 py-3 flex items-center justify-between">
      <h2 class="text-lg font-semibold text-gray-800 dark:text-gray-100">📋 {$t('dataBrowser.title')}</h2>
      <div class="flex gap-2">
        <button class="px-3 py-1.5 border border-gray-300 dark:border-gray-600 bg-white dark:bg-[#1C2333] hover:bg-gray-50 dark:hover:bg-gray-700/50 text-gray-700 dark:text-gray-300 text-sm rounded cursor-pointer" onclick={loadStatistics}>
          🔄 {$t('common.refresh')}
        </button>
        <button
          class="px-3 py-1.5 border rounded text-sm cursor-pointer {filterPanelVisible ? 'bg-blue-50 dark:bg-blue-900/30 border-blue-300 dark:border-blue-700 text-blue-600 dark:text-blue-400' : 'border-gray-300 dark:border-gray-600 bg-white dark:bg-[#1C2333] hover:bg-gray-50 dark:hover:bg-gray-700/50 text-gray-700 dark:text-gray-300'}"
          onclick={() => dataBrowserStore.toggleFilterPanel()}
        >
          🔍 {$t('dataBrowser.filter')}
        </button>
      </div>
    </div>

    {#if filterPanelVisible}
      <FilterPanel {activeTab} onApply={applyFilters} />
    {/if}

    {#if error}
      <div class="bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800 rounded p-3 text-red-600 dark:text-red-400 text-sm">{error}</div>
    {/if}

    <div class="flex-1 bg-white dark:bg-[#1C2333] rounded-lg shadow-sm overflow-hidden flex">
      <div class="flex-1 flex flex-col overflow-hidden">
        <div class="flex border-b border-gray-200 dark:border-gray-700">
          <button class="px-5 py-3 text-sm font-medium cursor-pointer {activeTab === 'vertices' ? 'text-blue-600 dark:text-blue-400 border-b-2 border-blue-500' : 'text-gray-500 dark:text-gray-400 hover:text-gray-700 dark:hover:text-gray-300'}" onclick={() => handleTabChange('vertices')}>
            📦 {$t('dataBrowser.vertices')}
          </button>
          <button class="px-5 py-3 text-sm font-medium cursor-pointer {activeTab === 'edges' ? 'text-blue-600 dark:text-blue-400 border-b-2 border-blue-500' : 'text-gray-500 dark:text-gray-400 hover:text-gray-700 dark:hover:text-gray-300'}" onclick={() => handleTabChange('edges')}>
            ↔ {$t('dataBrowser.edges')}
          </button>
        </div>

        <div class="p-4 flex-1 overflow-auto">
          {#if activeTab === 'vertices'}
            <div class="mb-4">
              <select class="px-3 py-1.5 border border-gray-300 dark:border-gray-600 rounded text-sm bg-white dark:bg-[#1C2333] text-gray-800 dark:text-gray-200" value={selectedTag || ''} onchange={handleTagChange}>
                <option value="">-- {$t('dataBrowser.selectTag')} --</option>
                {#each tags as tag (tag.name)}
                  <option value={tag.name}>{tag.name}</option>
                {/each}
              </select>
            </div>

            {#if loading}
              <div class="flex items-center justify-center p-8"><div class="animate-spin w-6 h-6 border-2 border-blue-500 border-t-transparent rounded-full"></div></div>
            {:else if vertices.length > 0}
              <div class="overflow-x-auto">
                <table class="w-full text-sm border-collapse">
                  <thead>
                    <tr class="bg-gray-50 dark:bg-gray-800/50">
                      <th class="px-3 py-2 text-left font-medium text-gray-600 dark:text-gray-400 border-b border-gray-200 dark:border-gray-700">ID</th>
                      <th class="px-3 py-2 text-left font-medium text-gray-600 dark:text-gray-400 border-b border-gray-200 dark:border-gray-700">{$t('schema.tags')}</th>
                      {#each vertexProperties as prop (prop)}
                        <th class="px-3 py-2 text-left font-medium text-gray-600 dark:text-gray-400 border-b border-gray-200 dark:border-gray-700">{prop}</th>
                      {/each}
                      <th class="px-3 py-2 text-left font-medium text-gray-600 dark:text-gray-400 border-b border-gray-200 dark:border-gray-700">{$t('common.actions')}</th>
                    </tr>
                  </thead>
                  <tbody>
                    {#each vertices as v (v.id)}
                      <tr class="hover:bg-gray-50 dark:hover:bg-gray-800/30">
                        <td class="px-3 py-1.5 border-b border-gray-100 dark:border-gray-700/50 font-mono text-xs text-gray-800 dark:text-gray-200">{v.id}</td>
                        <td class="px-3 py-1.5 border-b border-gray-100 dark:border-gray-700/50 text-gray-700 dark:text-gray-300">{v.tag}</td>
                        {#each vertexProperties as prop (prop)}
                          <td class="px-3 py-1.5 border-b border-gray-100 dark:border-gray-700/50 max-w-40 truncate text-gray-700 dark:text-gray-300">{formatCellValue(v.properties[prop])}</td>
                        {/each}
                        <td class="px-3 py-1.5 border-b border-gray-100 dark:border-gray-700/50">
                          <button class="text-blue-500 dark:text-blue-400 hover:text-blue-700 dark:hover:text-blue-300 text-xs cursor-pointer" onclick={() => showDetail(v, 'vertex')}>{$t('dataBrowser.viewDetail')}</button>
                          <button class="ml-2 text-green-600 dark:text-green-400 hover:text-green-700 dark:hover:text-green-300 text-xs cursor-pointer" onclick={() => viewInGraph(v, 'vertex')}>Graph</button>
                        </td>
                      </tr>
                    {/each}
                  </tbody>
                </table>
              </div>
              <div class="flex items-center justify-between mt-4 text-sm text-gray-500 dark:text-gray-400">
                <span>{$t('dataBrowser.total')}: {vertexTotal} {$t('dataBrowser.items')}</span>
                <div class="flex gap-2">
                  <button
                    class="px-3 py-1 border border-gray-300 dark:border-gray-600 rounded bg-white dark:bg-[#1C2333] hover:bg-gray-50 dark:hover:bg-gray-700/50 text-gray-700 dark:text-gray-300 cursor-pointer disabled:opacity-50"
                    disabled={vertexPage <= 1}
                    onclick={() => { dataBrowserStore.setVertexPage(vertexPage - 1); loadVertices(); }}
                  >{$t('common.prev')}</button>
                  <span class="px-3 py-1 text-gray-600 dark:text-gray-400">{$t('common.page')} {vertexPage}</span>
                  <button
                    class="px-3 py-1 border border-gray-300 dark:border-gray-600 rounded bg-white dark:bg-[#1C2333] hover:bg-gray-50 dark:hover:bg-gray-700/50 text-gray-700 dark:text-gray-300 cursor-pointer disabled:opacity-50"
                    disabled={vertexPage * vertexPageSize >= vertexTotal}
                    onclick={() => { dataBrowserStore.setVertexPage(vertexPage + 1); loadVertices(); }}
                  >{$t('common.next')}</button>
                </div>
              </div>
            {:else if selectedTag}
              <p class="text-gray-400 dark:text-gray-500 text-center py-8">{$t('schema.noTags')}</p>
            {:else}
              <p class="text-gray-400 dark:text-gray-500 text-center py-8">{$t('dataBrowser.selectTag')} {$t('common.loading')}</p>
            {/if}
          {:else}
            <div class="mb-4">
              <select class="px-3 py-1.5 border border-gray-300 dark:border-gray-600 rounded text-sm bg-white dark:bg-[#1C2333] text-gray-800 dark:text-gray-200" value={selectedEdgeType || ''} onchange={handleEdgeTypeChange}>
                <option value="">-- {$t('dataBrowser.selectEdgeType')} --</option>
                {#each edgeTypes as et (et.name)}
                  <option value={et.name}>{et.name}</option>
                {/each}
              </select>
            </div>

            {#if loading}
              <div class="flex items-center justify-center p-8"><div class="animate-spin w-6 h-6 border-2 border-blue-500 border-t-transparent rounded-full"></div></div>
            {:else if edges.length > 0}
              <div class="overflow-x-auto">
                <table class="w-full text-sm border-collapse">
                  <thead>
                    <tr class="bg-gray-50 dark:bg-gray-800/50">
                      <th class="px-3 py-2 text-left font-medium text-gray-600 dark:text-gray-400 border-b border-gray-200 dark:border-gray-700">ID</th>
                      <th class="px-3 py-2 text-left font-medium text-gray-600 dark:text-gray-400 border-b border-gray-200 dark:border-gray-700">{$t('common.type')}</th>
                      <th class="px-3 py-2 text-left font-medium text-gray-600 dark:text-gray-400 border-b border-gray-200 dark:border-gray-700">Source</th>
                      <th class="px-3 py-2 text-left font-medium text-gray-600 dark:text-gray-400 border-b border-gray-200 dark:border-gray-700">Target</th>
                      <th class="px-3 py-2 text-left font-medium text-gray-600 dark:text-gray-400 border-b border-gray-200 dark:border-gray-700">Rank</th>
                      {#each edgeProperties as prop (prop)}
                        <th class="px-3 py-2 text-left font-medium text-gray-600 dark:text-gray-400 border-b border-gray-200 dark:border-gray-700">{prop}</th>
                      {/each}
                      <th class="px-3 py-2 text-left font-medium text-gray-600 dark:text-gray-400 border-b border-gray-200 dark:border-gray-700">{$t('common.actions')}</th>
                    </tr>
                  </thead>
                  <tbody>
                    {#each edges as e (e.id)}
                      <tr class="hover:bg-gray-50 dark:hover:bg-gray-800/30">
                        <td class="px-3 py-1.5 border-b border-gray-100 dark:border-gray-700/50 font-mono text-xs text-gray-800 dark:text-gray-200">{e.id}</td>
                        <td class="px-3 py-1.5 border-b border-gray-100 dark:border-gray-700/50 text-gray-700 dark:text-gray-300">{e.type}</td>
                        <td class="px-3 py-1.5 border-b border-gray-100 dark:border-gray-700/50 font-mono text-xs text-gray-800 dark:text-gray-200">{e.src}</td>
                        <td class="px-3 py-1.5 border-b border-gray-100 dark:border-gray-700/50 font-mono text-xs text-gray-800 dark:text-gray-200">{e.dst}</td>
                        <td class="px-3 py-1.5 border-b border-gray-100 dark:border-gray-700/50 text-gray-700 dark:text-gray-300">{e.rank}</td>
                        {#each edgeProperties as prop (prop)}
                          <td class="px-3 py-1.5 border-b border-gray-100 dark:border-gray-700/50 max-w-40 truncate text-gray-700 dark:text-gray-300">{formatCellValue(e.properties[prop])}</td>
                        {/each}
                        <td class="px-3 py-1.5 border-b border-gray-100 dark:border-gray-700/50">
                          <button class="text-blue-500 dark:text-blue-400 hover:text-blue-700 dark:hover:text-blue-300 text-xs cursor-pointer" onclick={() => showDetail(e, 'edge')}>{$t('dataBrowser.viewDetail')}</button>
                          <button class="ml-2 text-green-600 dark:text-green-400 hover:text-green-700 dark:hover:text-green-300 text-xs cursor-pointer" onclick={() => viewInGraph(e, 'edge')}>Graph</button>
                        </td>
                      </tr>
                    {/each}
                  </tbody>
                </table>
              </div>
              <div class="flex items-center justify-between mt-4 text-sm text-gray-500 dark:text-gray-400">
                <span>{$t('dataBrowser.total')}: {edgeTotal} {$t('dataBrowser.items')}</span>
                <div class="flex gap-2">
                  <button
                    class="px-3 py-1 border border-gray-300 dark:border-gray-600 rounded bg-white dark:bg-[#1C2333] hover:bg-gray-50 dark:hover:bg-gray-700/50 text-gray-700 dark:text-gray-300 cursor-pointer disabled:opacity-50"
                    disabled={edgePage <= 1}
                    onclick={() => { dataBrowserStore.setEdgePage(edgePage - 1); loadEdges(); }}
                  >{$t('common.prev')}</button>
                  <span class="px-3 py-1 text-gray-600 dark:text-gray-400">{$t('common.page')} {edgePage}</span>
                  <button
                    class="px-3 py-1 border border-gray-300 dark:border-gray-600 rounded bg-white dark:bg-[#1C2333] hover:bg-gray-50 dark:hover:bg-gray-700/50 text-gray-700 dark:text-gray-300 cursor-pointer disabled:opacity-50"
                    disabled={edgePage * edgePageSize >= edgeTotal}
                    onclick={() => { dataBrowserStore.setEdgePage(edgePage + 1); loadEdges(); }}
                  >{$t('common.next')}</button>
                </div>
              </div>
            {:else if selectedEdgeType}
              <p class="text-gray-400 dark:text-gray-500 text-center py-8">{$t('schema.noEdges')}</p>
            {:else}
              <p class="text-gray-400 dark:text-gray-500 text-center py-8">{$t('dataBrowser.selectEdgeType')} {$t('common.loading')}</p>
            {/if}
          {/if}
        </div>
      </div>

      <!-- Statistics Panel -->
      <div class="w-64 border-l border-gray-200 dark:border-gray-700 p-4 bg-gray-50 dark:bg-gray-800/20 overflow-y-auto">
        <h3 class="font-semibold text-gray-800 dark:text-gray-100 mb-3 text-sm">{$t('sidebar.stats')}</h3>
        {#if statistics}
          <div class="space-y-2 text-sm">
            <div class="flex justify-between"><span class="text-gray-500 dark:text-gray-400">{$t('dataBrowser.vertices')}:</span><span class="font-medium text-gray-800 dark:text-gray-200">{statistics.totalVertices ?? '-'}</span></div>
            <div class="flex justify-between"><span class="text-gray-500 dark:text-gray-400">{$t('dataBrowser.edges')}:</span><span class="font-medium text-gray-800 dark:text-gray-200">{statistics.totalEdges ?? '-'}</span></div>
            <div class="flex justify-between"><span class="text-gray-500 dark:text-gray-400">{$t('schema.tags')}:</span><span class="font-medium text-gray-800 dark:text-gray-200">{statistics.tagCount ?? '-'}</span></div>
            <div class="flex justify-between"><span class="text-gray-500 dark:text-gray-400">{$t('schema.edges')}:</span><span class="font-medium text-gray-800 dark:text-gray-200">{statistics.edgeTypeCount ?? '-'}</span></div>
          </div>
        {:else}
          <p class="text-gray-400 dark:text-gray-500 text-xs">{$t('common.refresh')} {$t('common.loading')}</p>
        {/if}
      </div>
    </div>
  </div>
{:else}
  <div class="bg-white dark:bg-[#1C2333] rounded-lg shadow-sm p-8 text-center">
    <p class="text-gray-500 dark:text-gray-400">{$t('common.select')} {$t('sidebar.spaces')} {$t('common.loading')}</p>
  </div>
{/if}

<!-- Detail Modal -->
{#if detailModalVisible && detailData}
  <div class="fixed inset-0 z-50 flex items-center justify-center">
    <div role="presentation" class="absolute inset-0 bg-black/20" onclick={() => dataBrowserStore.hideDetail()}></div>
    <div class="relative bg-white dark:bg-[#1C2333] rounded-lg shadow-lg p-6 w-96 max-h-[80vh] overflow-y-auto">
      <div class="flex items-center justify-between mb-4">
        <h3 class="font-semibold text-gray-800 dark:text-gray-100">{detailType === 'vertex' ? $t('dataBrowser.vertices') : $t('dataBrowser.edges')} {$t('common.detail')}</h3>
        <button class="text-gray-400 dark:text-gray-500 hover:text-gray-600 dark:hover:text-gray-300 cursor-pointer" onclick={() => dataBrowserStore.hideDetail()}>✕</button>
      </div>
      <div class="space-y-2">
        {#each Object.entries(detailData) as [key, value] (key)}
          {#if key !== 'properties'}
            <div class="text-sm"><span class="text-gray-500 dark:text-gray-400">{key}:</span> <span class="ml-1 text-gray-800 dark:text-gray-200">{String(value)}</span></div>
          {/if}
        {/each}
        {#if detailData.properties}
          <div class="mt-4">
            <h4 class="text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">{$t('common.properties')}</h4>
            {#each Object.entries(detailData.properties) as [k, v] (k)}
              <div class="text-sm ml-2"><span class="text-gray-500 dark:text-gray-400">{k}:</span> <span class="ml-1 text-gray-800 dark:text-gray-200">{String(v)}</span></div>
            {/each}
          </div>
        {/if}
      </div>
    </div>
  </div>
{/if}
